#import openai_secret_manager
import openai
import requests

openai_api_key = "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"

openai.api_key = openai_api_key

#prompt = "the player will try to convince an NPC called Rin to go on a date with them. Rin hates pick-up lines and anything that is corny or cheesy. If Rin gets angry, she will leave and the player will lose the game.\nPlayer: Hi! How are you?"
prompt = "In a dating simulator, the player will talk with an NPC called Rin, the player's dialogue will only be generated by the user (prompts). Rin hates pick-up lines and corny or cheesy stuff. If the player makes Rin angry, she will leave.\n"

p = input("Player: ")
p = "Player: " + p + "\n"

prompt = prompt + p

response = openai.Completion.create(
    engine="text-davinci-002",
    prompt=(prompt),
    max_tokens=256,
    n = 1,
    stop=None,
    temperature=0.7,
)

r = response["choices"][0]["text"]
print(f"\n{r}")
prompt = prompt + response["choices"][0]["text"]

while True:
    p = input("Player: ")
    p = "Player: " + p + "\n"

    prompt = prompt + p

    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=(prompt),
        max_tokens=256,
        n = 1,
        stop=None,
        temperature=0.7,
    )

    print(response["choices"][0]["text"])
